
package sample.jooq.domain;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


@Generated(value = { "http:		"jOOQ version:3.8.2" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStore extends TableImpl<Record> {

	private static final long serialVersionUID = -2132596210;

	
	public static final BookStore BOOK_STORE = new BookStore();

	
	@Override
	public Class<Record> getRecordType() {
		return Record.class;
	}

	
	public final TableField<Record, String> NAME = createField("NAME",
			org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	
	public BookStore() {
		this("BOOK_STORE", null);
	}

	
	public BookStore(String alias) {
		this(alias, BOOK_STORE);
	}

	private BookStore(String alias, Table<Record> aliased) {
		this(alias, aliased, null);
	}

	private BookStore(String alias, Table<Record> aliased, Field<?>[] parameters) {
		super(alias, null, aliased, parameters, "");
	}

	
	@Override
	public Schema getSchema() {
		return Public.PUBLIC;
	}

	
	@Override
	public List<UniqueKey<Record>> getKeys() {
		return Arrays.<UniqueKey<Record>>asList(Keys.CONSTRAINT_F);
	}

	
	@Override
	public BookStore as(String alias) {
		return new BookStore(alias, this);
	}

	
	@Override
	public BookStore rename(String name) {
		return new BookStore(name, null);
	}
}
