
package sample.jooq.domain;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


@Generated(value = { "http:		"jOOQ version:3.8.2" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

	private static final long serialVersionUID = -1557925562;

	
	public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

	
	public final Public PUBLIC = sample.jooq.domain.Public.PUBLIC;

	
	private DefaultCatalog() {
		super("");
	}

	@Override
	public final List<Schema> getSchemas() {
		List result = new ArrayList();
		result.addAll(getSchemas0());
		return result;
	}

	private final List<Schema> getSchemas0() {
		return Arrays.<Schema>asList(Public.PUBLIC);
	}
}
